name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Run
        run: |
          echo -e "Ivanov\n2\n5 5 5 5 5\nPetrov\n1\n3 3 3 3 3\nSidorov\n3\n5 5 5 5 5\nKuznetsov\n2\n4 4 4 4 4\nSmirnov\n1\n2 2 2 2 2\nFedorov\n3\n5 5 5 5 5\nMikhailov\n2\n3 3 3 3 3\nAlexeev\n1\n4 4 4 4 4\nVasiliev\n3\n5 5 5 4 5\nNikolaev\n2\n4 4 5 5 4" | ./bin/lab2_task3
